name       : gawk
version    : 5.2.0
release    : 20
source     :
    - https://ftp.gnu.org/gnu/gawk/gawk-5.2.0.tar.xz : e4ddbad1c2ef10e8e815ca80208d0162d4c983e6cca16f925e8418632d639018
homepage   : https://www.gnu.org/software/gawk
license    : GPL-3.0-or-later
component  : system.base
summary    : gawk - GNU Awk (Data extraction and reporting tool)
description: |
    gawk (GNU awk) is a tool used for data extraction and reporting from files, often used in file manipulation.
patterns   :
    - devel : [/usr/share/man/man3]
optimize   :
    - lto
setup      : |
    %configure
build      : |
    %make
profile    : |
    ./gawk 'BEGIN{for (i=1;i<=10000000;i++) print (i%5?"miss":"hit"),i,"  third\t \tfourth"}' > file
    echo "/hit [[:digit:]]*0 / { print \$4, \$1, \$3 }" > test.awk
    ./gawk -f test.awk file | ./gawk '!seen[$0]++{unq++;r=$0} END{print ((unq==1) && (seen[r]==1000000) && (r=="fourth hit third")) ? "PASS" : "FAIL"}'
install    : |
    %make_install
    rm $installdir/usr/bin/*awk-*

    install -d -m00755 $installdir/usr/share/defaults/etc
    mv $installdir/etc $installdir/usr/share/defaults

    ln -s /usr/share/man/man1/gawk.1 $installdir/usr/share/man/man1/awk.1
