name       : gawk
version    : 4.2.1
release    : 12
source     :
    - https://ftp.gnu.org/gnu/gawk/gawk-4.2.1.tar.xz : d1119785e746d46a8209d28b2de404a57f983aa48670f4e225531d3bdc175551
    - https://packages.solus-project.com/shannon/m/mpfr/mpfr-3.1.6-5-1-x86_64.eopkg : 2c703594e21e22840f091ca9b84571e64dc9e540b3d670ac92e5455d3595d846
homepage   : https://www.gnu.org/software/gawk
license    : GPL-3.0-or-later
component  : system.base
summary    : gawk - GNU Awk (Data extraction and reporting tool)
description: |
    gawk (GNU awk) is a tool used for data extraction and reporting from files, often used in file manipulation.
patterns   :
    - devel : [/usr/share/man/man3]
setup      : |
    uneopkg $sources/mpfr-3.1.6-5-1-x86_64.eopkg
    export LD_LIBRARY_PATH="/usr/lib64:/usr/lib64/libfakeroot:$workdir/install/usr/lib64"
    %configure
build      : |
    export LD_LIBRARY_PATH="/usr/lib64:/usr/lib64/libfakeroot:$workdir/install/usr/lib64"
    %make
install    : |
    export LD_LIBRARY_PATH="/usr/lib64:/usr/lib64/libfakeroot:$workdir/install/usr/lib64"
    %make_install
    rm $installdir/usr/bin/*awk-*

    install -d -m00755 $installdir/usr/share/defaults/etc
    mv $installdir/etc $installdir/usr/share/defaults

    ln -s /usr/share/man/man1/gawk.1 $installdir/usr/share/man/man1/awk.1
