name        : gawk
version     : 4.1.1
release     : 4
source      :
    - http://ftp.gnu.org/gnu/gawk/gawk-4.1.1.tar.xz : efd4c6aafb1ce996309fc903ceb625e7012221c464eb72483dbb23adef1ee8db
homepage    : http://www.gnu.org/software/gawk
license     :
    - GPLv3+
summary     : gawk - GNU Awk (Data extraction and reporting tool)
description : |
    gawk (GNU awk) is a tool used for data extraction and reporting from files, often used in file manipulation.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/usr/bin/*awk-*

