name       : gawk
version    : 4.1.4
release    : 8
source     :
    - http://ftp.gnu.org/gnu/gawk/gawk-4.1.4.tar.xz : 53e184e2d0f90def9207860531802456322be091c7b48f23fdc79cda65adc266
homepage   : http://www.gnu.org/software/gawk
license    : GPL-3.0
component  : system.base
summary    : gawk - GNU Awk (Data extraction and reporting tool)
description: |
    gawk (GNU awk) is a tool used for data extraction and reporting from files, often used in file manipulation.
patterns   :
    - devel: [/usr/share/man/man3]
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/usr/bin/*awk-*
    ln -s /usr/share/man/man1/gawk.1 $installdir/usr/share/man/man1/awk.1
