name       : gawk
version    : 5.0.0
release    : 14
source     :
    - https://ftp.gnu.org/gnu/gawk/gawk-5.0.0.tar.xz : 50f091ed0eb485ad87dbb620d773a3e2c31a27f75f5e008f7bf065055f024406
homepage   : https://www.gnu.org/software/gawk
license    : GPL-3.0-or-later
component  : system.base
summary    : gawk - GNU Awk (Data extraction and reporting tool)
description: |
    gawk (GNU awk) is a tool used for data extraction and reporting from files, often used in file manipulation.
patterns   :
    - devel : [/usr/share/man/man3]
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/*awk-*

    install -d -m00755 $installdir/usr/share/defaults/etc
    mv $installdir/etc $installdir/usr/share/defaults

    ln -s /usr/share/man/man1/gawk.1 $installdir/usr/share/man/man1/awk.1
